spring.application.name=demo

# Conexión a MySQL (XAMPP usa el puerto 3306 por defecto)
spring.datasource.url=jdbc:mysql://localhost:3306/liga_padel?createDatabaseIfNotExist=true&serverTimezone=UTC
spring.datasource.username=root
# En XAMPP la contraseña de root suele estar vacía
spring.datasource.password=

# Hibernate: Crea las tablas automáticamente basándose en tus clases @Entity
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true